source: _source
destination: _site
baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://linuxsimba.com" # the base hostname & protocol for your site
title: "Linux Simba"
social_media_btn:
  - name: 'twitter'
    url: 'https://twitter.com/intent/follow?original_referer=http%3A%2F%2Flinuxsimb.com&amp;region=follow_link&amp;screen_name=skamithik&amp;tw_p=followbutton'
    title: 'Follow Me (@skamithik) on Twitter'
    id: 'twitter_btn'
  - name: 'linkedin'
    url: 'https://www.linkedin.com/profile/view?id=147021940'
    title: 'Connect with me on LinkedIn'
    id: 'linkedin_btn'
# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."
markdown: redcarpet

gems:
  - jemoji
  - jekyll-last-modified-at
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "Guardfile"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
